---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org2-tls-root-cert-issuer
  namespace: org2
  labels:
    app.kubernetes.io/name: org2-ca-tls
    app.kubernetes.io/part-of: org2
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org2-tls-cert-issuer
  namespace: org2
  labels:
    app.kubernetes.io/name: org2-ca-tls
    app.kubernetes.io/part-of: org2
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: org2-tls-ca
  secretName: org2-tls-cert-issuer
  issuerRef:
    name: org2-tls-root-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org2-tls-cert-issuer
  namespace: org2
  labels:
    app.kubernetes.io/name: org2-ca-tls
    app.kubernetes.io/part-of: org2
spec:
  ca:
    secretName: org2-tls-cert-issuer


