---
apiVersion: v1
kind: ConfigMap
metadata:
  name: org2-peers-env
  namespace: org2
  labels:
    app.kubernetes.io/name: org2-peers-env
    app.kubernetes.io/part-of: org2
data:
  FABRIC_CFG_PATH: /config

  FABRIC_LOGGING_SPEC: INFO

  CORE_PEER_NETWORKID: dev

  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052

  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /config/tls/tls.crt
  CORE_PEER_TLS_KEY_FILE: /config/tls/tls.key
  CORE_PEER_TLS_ROOTCERT_FILE: /config/tls/ca.crt

  CORE_PEER_FILESYSTEMPATH: /data

  CORE_PEER_LOCALMSPID: Org2MSP
  CORE_PEER_MSPCONFIGPATH: /config/msp

  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP: "20"
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984

  CORE_LEDGER_SNAPSHOTS_ROOTDIR: /data/snapshots

  CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443
  CORE_OPERATIONS_TLS_ENABLED: "false"

  CORE_METRICS_PROVIDER: "disabled"
