---
apiVersion: v1
kind: ConfigMap
metadata:
  name: org2-peer1-env
  namespace: org2
  labels:
    app.kubernetes.io/name: org2-peer1-env
    app.kubernetes.io/part-of: org2
data:
  CORE_PEER_ID: org2-peer1
  CORE_PEER_CHAINCODEADDRESS: org2-peer1:7052
  CORE_PEER_ADDRESS: org2-peer1:7051
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: org2-peer1.org2.svc.cluster.local:7051
  CORE_PEER_GOSSIP_BOOTSTRAP: org2-peer2:7051
