---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org0-root-cert-issuer
  namespace: org0
  labels:
    app.kubernetes.io/name: org0-ca
    app.kubernetes.io/part-of: org0
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org0-cert-issuer
  namespace: org0
  labels:
    app.kubernetes.io/name: org0-ca
    app.kubernetes.io/part-of: org0
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: org0-ca
  secretName: org0-cert-issuer
  issuerRef:
    name: org0-root-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org0-cert-issuer
  namespace: org0
  labels:
    app.kubernetes.io/name: org0-ca
    app.kubernetes.io/part-of: org0
spec:
  ca:
    secretName: org0-cert-issuer


